# Q.1.

In [1]:
import pandas as pd
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Yes, there is a difference  

list_ is a list type of data structure   and array_list is an n-dimensional array

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

# Q.2.

In [5]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [6]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q.3.

In [7]:
array_list = np.array(object = list_, dtype = int)

In [8]:
array_list

array([1, 2, 3, 4, 5])

The datatype of elements of array-list will change to integer but the datatype of list_ will remain same

In [9]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [10]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


# Q.4.

In [11]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [12]:
num_array.shape

(2, 3)

In [13]:
num_array.size

6

# Q.5.

In [14]:
zero_matrix = np.zeros((3,3))

In [15]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q.6.

In [16]:
idt = np.eye(5)

In [17]:
idt

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])